name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: checkout
      uses: actions/checkout@v2

    - name: get dependencies
      run: go get -v -t -d ./...
    
    - name: schema
      run: ./schema.py && ./concourse-schema.py 

    - name: build
      run: ./devlib/buildgo.py --all

    - name: test
      run: YTT_LINT_SCHEMA_PATH="$PWD/vscode/schema/" go test ./...
